# Generated by Django 3.1 on 2020-08-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name_verified',
            field=models.BooleanField(default=False),
        ),
    ]
